name: Condition User Input Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'prod'

    steps:
      - run: echo "Deploying to Production"