name: Condition If Failure Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Step 1
        run: echo "Hello"

      - name: step 2
        if: failure()
        run: echo "Runs only if Step 1 failed"