name: Env Variables Secrets Demo

on: workflow_dispatch

env:
  GLOBAL_ENV: "global-value"

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: prod  

    steps:
      - name: Use environment variables
        env:
          API_URL: ${{ vars.API_URL }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Deploying to $API_URL"
          echo "DB password length: ${#DB_PASS}"
          echo "DB password is ${DB_PASS}"