name: Env Variables Consume Demo

on: workflow_dispatch

env:
  GLOBAL_ENV: "global-value"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Use environment variables
        env:
          API_URL: ${{ vars.API_URL }}
          APP_MODE: ${{ vars.APP_MODE }}
        run: |
          echo "API URL: $API_URL"
          echo "APP MODE: $APP_MODE"
